"use client";

import React, { useState, useEffect } from "react";

const FALLBACK_ADVISORY = {
  station_name: "Anand Vihar, Delhi - CPCB",
  predicted_aqi_24h: 395,
  alert_level: "Severe",
  recommendations: "Enforce Stage 4 of the Graded Response Action Plan (GRAP) immediately. Ban entry of heavy diesel trucks into Delhi (except for essential commodities). Halt all construction and demolition activities. Transition all primary and secondary schools to online learning, and mandate a 50% work-from-home policy for offices across the Delhi NCR region.",
  timestamp: new Date().toISOString()
};

export default function RecommendationsPage() {
  const [advisory, setAdvisory] = useState<any>(FALLBACK_ADVISORY);
  const [loading, setLoading] = useState(false);
  const [apiSource, setApiSource] = useState("Local Simulation Cache");

  useEffect(() => {
    // Attempt to query the latest advisory from the backend API database
    fetch("http://localhost:8000/api/advisory")
      .then(res => {
        if (!res.ok) throw new Error("API Offline");
        return res.json();
      })
      .then(data => {
        if (data && data.length > 0) {
          setAdvisory(data[0]); // Take the latest prediction advisory
          setApiSource("Live Gemini 2.5 Flash Agent");
        }
      })
      .catch(err => {
        console.log("Using default fallback policy advisory: ", err.message);
        setApiSource("Local Simulation Cache");
      });
  }, []);

  // Check list items based on GRAP Stage IV guidelines
  const grapStage = advisory.predicted_aqi_24h > 300 ? "Stage IV (Emergency)" : (advisory.predicted_aqi_24h > 200 ? "Stage III (Very Poor)" : "Stage II (Poor)");
  
  const initialActions = [
    { id: 1, text: "Ban entry of non-essential commercial diesel trucks into Delhi", checked: true },
    { id: 2, text: "Suspend all civil and private construction and demolition activities", checked: true },
    { id: 3, text: "Transition physical classes in schools to online learning modes", checked: true },
    { id: 4, text: "Deploy anti-smog water sprinklers and mechanical sweepers along high-traffic corridors", checked: false },
    { id: 5, text: "Mandate 50% work-from-home capacity for state/municipal offices", checked: false }
  ];
  
  const [actions, setActions] = useState(initialActions);

  const toggleAction = (id: number) => {
    setActions(actions.map(a => a.id === id ? { ...a, checked: !a.checked } : a));
  };

  return (
    <div className="space-y-8 animate-fade-in">
      
      {/* Title */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="font-heading font-bold text-3xl text-slate-100">
            Administrative Policy Interventions
          </h2>
          <p className="text-slate-400 text-sm">
            Urban policy recommendations and Graded Response Action Plan (GRAP) checklists generated by the Advisory Agent.
          </p>
        </div>
        
        <span className="px-3 py-1.5 rounded-full text-xs font-semibold bg-slate-800 text-slate-300 border border-slate-700/60">
          Source: <span className="font-bold text-emerald-400">{apiSource}</span>
        </span>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Status card */}
        <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/40 backdrop-blur-md flex flex-col justify-between">
          <div>
            <h3 className="text-slate-400 text-xs font-semibold uppercase tracking-wider mb-2">
              Active Trigger Status
            </h3>
            
            <div className="mt-4 space-y-4">
              <div>
                <p className="text-[10px] text-slate-500 uppercase font-bold">Target Station</p>
                <p className="text-sm font-semibold text-slate-200 mt-0.5">{advisory.station_name.split(",")[0]}</p>
              </div>
              
              <div>
                <p className="text-[10px] text-slate-500 uppercase font-bold">Predicted AQI (24h)</p>
                <p className="text-4xl font-heading font-black text-rose-500 mt-1">{advisory.predicted_aqi_24h}</p>
              </div>
              
              <div>
                <p className="text-[10px] text-slate-500 uppercase font-bold">Policy Stage Trigger</p>
                <span className="inline-block px-3 py-1 rounded bg-purple-500/10 text-purple-400 border border-purple-500/20 text-xs font-bold mt-2">
                  {grapStage}
                </span>
              </div>
            </div>
          </div>

          <div className="mt-8 pt-4 border-t border-slate-800/60 text-[10px] text-slate-500">
            Advisory compiled on {new Date(advisory.timestamp).toLocaleString()}
          </div>
        </div>

        {/* Gemini recommendations text */}
        <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/40 backdrop-blur-md lg:col-span-2">
          <h3 className="font-heading font-bold text-base text-slate-200 mb-4 flex items-center gap-2">
            <span>🤖</span> Gemini-Generated Policy Recommendations
          </h3>
          
          <div className="p-5 rounded-xl bg-slate-950/60 border border-slate-800/80 text-sm leading-relaxed text-slate-300">
            {advisory.recommendations}
          </div>

          <div className="mt-6 flex gap-4 text-xs text-slate-400">
            <span className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-emerald-500" />
              Evidence-Backed Interventions
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-emerald-500" />
              GRAP Compliant Guidelines
            </span>
          </div>
        </div>
      </div>

      {/* Action Item Checklists */}
      <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/20 backdrop-blur-md">
        <h3 className="font-heading font-bold text-lg text-slate-200 mb-2">
          Administrator Action Checklist
        </h3>
        <p className="text-slate-400 text-xs mb-6">
          Track executive compliance of active GRAP emergency directions for Delhi agencies.
        </p>

        <div className="space-y-3">
          {actions.map((act) => (
            <div 
              key={act.id} 
              onClick={() => toggleAction(act.id)}
              className={`p-4 rounded-xl border transition-all duration-150 flex items-center gap-4 cursor-pointer select-none ${act.checked ? 'bg-slate-950/80 border-slate-800 text-slate-100' : 'bg-slate-900/10 border-slate-800/40 text-slate-400 hover:border-slate-800'}`}
            >
              <div className={`w-5 h-5 rounded flex items-center justify-center border transition-all duration-150 ${act.checked ? 'bg-emerald-500 border-emerald-600 text-white' : 'border-slate-700 bg-slate-950'}`}>
                {act.checked && "✓"}
              </div>
              <span className="text-sm font-semibold">{act.text}</span>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
}
